#include <linux/ioctl.h>

#define IOC_MOTOR_MAGIC 'K'

#define MOTOR_TEST _IO(IOC_MOTOR_MAGIC, 0)
#define MOTOR_SET_VOLTAGE _IO(IOC_MOTOR_MAGIC, 1)
#define MOTOR_GET_VOLTAGE _IO(IOC_MOTOR_MAGIC, 2)
#define MOTOR_SET_MAX_VOLTAGE _IO(IOC_MOTOR_MAGIC, 3)
#define MOTOR_GET_MAX_VOLTAGE _IO(IOC_MOTOR_MAGIC, 4)
#define MOTOR_SET_PWM_PERIOD _IO(IOC_MOTOR_MAGIC, 5)
#define MOTOR_GET_PWM_PERIOD _IO(IOC_MOTOR_MAGIC, 6)
#define MOTOR_SET_STATE _IO(IOC_MOTOR_MAGIC, 7)
#define MOTOR_GET_STATE _IO(IOC_MOTOR_MAGIC, 8)
#define MOTOR_GET_POSITION _IO(IOC_MOTOR_MAGIC, 9)
